FROM node:18-alpine AS build

# Build Args for Environment Variables
ARG PORT
ARG MONGO_URL
ARG CORS_ORIGIN_URL
ARG AUTH0_DOMAIN
ARG AUTH0_AUDIENCE

# Set as Environment Variables in Container
ENV PORT=$PORT
ENV MONGO_URL=$MONGO_URL
ENV CORS_ORIGIN_URL=$CORS_ORIGIN_URL
ENV AUTH0_DOMAIN=$AUTH0_DOMAIN
ENV AUTH0_AUDIENCE=$AUTH0_AUDIENCE

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 9000
CMD ["npm", "run", "prod"]